### ISSUE TITLE
Deck and Card (Jonathan)

### ISSUE THREAD

**Issue by jonathanharijanto** [cs361-W16/Blackjack-2#3]
Card: As a player, I want cards and a deck to be able to play the game.

Conversation: There are four suits with 13 possible face values, making 52 (unique) cards minus jokers. Suits are: hearts, spades, clubs, diamonds. Face values go from Ace (one) to 10, along with jack (11), queen (12), king (13). These are not the actual values as they are played, but these ones are how we tell the cards apart.

Confirmation: Cards should have a suit and value. Each deck should have 52 cards at the start.

**Comment by kirkpatt** [comment]
Seems we never closed this one. But the deck and cards are functional.
